dist: trusty
language: cpp
before_install:
  - sudo apt-get update -qq
  # Install Bison, Flex, CMAKE
  - sudo apt-get -qq install bison flex wget cmake
  # Install readline
  - sudo apt–get install libreadline6 libreadline6–dev
  # Install gperf
  - sudo apt-get install gperf
  # Install autoconf
  - sudo apt-get install autoconf
  # Clone Icarus Verilog GIT repository
  - git clone https://github.com/steveicarus/iverilog.git
  # Build the IVerilog from sources
  - cd iverilog && sh autoconf.sh && ./configure && make && make install
script:
  - bash ./test.sh
