dist: trusty
language: cpp
before_install:
  # Add Yosys repository
  - sudo add-apt-repository -y "ppa:saltmakrell/ppa"
  # Perform update
  - sudo apt-get update -qq
  # Install Yosys
  - sudo apt-get install yosys
script:
  - bash ./synth.sh
